### ISSUE TITLE
BUG - GIST ERROR

### ISSUE THREAD

**Issue by simonwjackson** [kenhowardpdx/vscode-gist#11] opened 2017-09-12 19:20 UTC
**This is a**

- [x ] bug report

#### Description
On every file save i get the following error:

`GIST ERROR: {"message":"Server Error", "documentation_url": "https://developer.github.com/v3/gists/#edit-a-gist"} [github]`

**Comment by kenhowardpdx** [comment] 2017-09-12 20:28
@simonwjackson thank you for the bug report.

**Comment by kenhowardpdx** [comment] 2017-09-12 21:06
@simonwjackson I can't reproduce this specific error but did uncover some undesired behavior in #12 

Can you list the steps you took to re-produce this bug? And if possible (not required) screen capture it either in video or in LICEcap
![bug](https://user-images.githubusercontent.com/1892667/30348250-95240d5e-97c3-11e7-875e-be30f455eef0.gif)

**Comment by kenhowardpdx** [comment] 2017-11-08 11:52
Closing. If this issue still exists please re-open.

**Closed by kenhowardpdx** 2017-11-08 11:52 UTC
Labels: bug, investigate
