### ISSUE TITLE
awesome tool can we use this on Github Enterprise? please...

### ISSUE THREAD

**Issue by suifeng330104970** [kenhowardpdx/vscode-gist#53] opened 2018-11-14 08:43 UTC
**This is a**

- [ ] bug report
- [ ] feature request

**Comment by suifeng330104970** [comment] 2018-11-14 08:43
feature request

**Comment by kenhowardpdx** [comment] 2018-11-15 04:56
Duplicate of #51

**Closed by kenhowardpdx** 2018-11-15 04:56 UTC
